
// Posts
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_SINGLE_PROFILE = 'FETCH_SINGLE_PROFILE';
export const RESET_SINGLE_PROFILE = 'RESET_SINGLE_PROFILE';